services:
  app:
    build: .
    command: ./.docker/start.sh
    container_name: micro-videos-admin-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - '/etc/timezone:/etc/localtime:ro'
      - '/etc/localtime:/etc/localtime:ro'

  db:
    platform: linux/amd64
    image: mysql:8.0.40-debian
    container_name: micro-videos-admin-db
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    # volumes:
    #   - ./.docker/mysql:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
